config/routes.rb
Rails.application.routes.draw do
  resources :ingredients, only: %i[index show new create update destroy]
  resources :ingredient_categories, only: %i[index show new create update destroy]
  resources :recipes, only: %i[index show new create update destroy] do
    resources :recipe_ingredients, only: %i[new]
  end
  resources :recipe_ingredients, only: %i[create update destroy]
  resources :mealtimes, only: %i[index show new create update destroy] do
    resources :recipe_meals, only: %i[new]
    resources :ingredient_meals, only: %i[new]
    resources :custom_meals, only: %i[new show]
  end
  resources :recipe_meals, only: %i[create update destroy]
  resources :ingredient_meals, only: %i[create update destroy]
  resources :custom_meals, only: %i[create update destroy]
  resources :protocols, only: %i[index show new]
  resources :weight_protocol_entries, only: %i[create update destroy]

  namespace :api do
    namespace :v1 do
      resources :ingredients, only: %i[index show create update destroy]
      resources :ingredient_categories, only: %i[index show create update destroy]
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :mealtimes

  validates :name, :portions, presence: true

  def energy
    sum = 0
    recipe_ingredients.each do |ingredient|
      sum += (ingredient.amount / 100.0) * ingredient.ingredient.energy
    end
    sum / portions
  end

  def carbo
    sum = 0
    recipe_ingredients.each do |ingredient|
      sum += (ingredient.amount / 100.0) * ingredient.ingredient.carbo
    end
    sum / portions
  end

  def protein
    sum = 0
    recipe_ingredients.each do |ingredient|
      sum += (ingredient.amount / 100.0) * ingredient.ingredient.protein
    end
    sum / portions
  end

  def fat
    sum = 0
    recipe_ingredients.each do |ingredient|
      sum += (ingredient.amount / 100.0) * ingredient.ingredient.fat
    end
    sum / portions
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show update destroy]

  # GET /recipes
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  def show; end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :show
    end
  end

  # DELETE /recipes/1
  def destroy
    if @recipe.destroy
      redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
    else
      redirect_to recipes_url, notice: 'Recipe could not be destroyed.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :portions)
  end
end

app/views/recipes/_form.html.haml
= bootstrap_form_for(recipe) do |f|
  - if recipe.errors.any?
    #error_explanation
      %h2
        = pluralize(recipe.errors.count, "error")
        prohibited this recipe from being saved:

      %ul
      - recipe.errors.full_messages.each do |message|
        %li
          = message

  = f.text_field :name
  = f.number_field :portions

  .actions
    = f.submit "Save", class: "btn btn-primary"
    - if recipe.persisted?
      = link_to 'Delete', recipe, data: {:confirm => 'Are you sure?'}, method: :delete, class: "btn btn-default"
    = link_to 'Back', recipes_path, class: "btn btn-default"

- if recipe.persisted?
  %table
    %tr
      %th
        Amount
      %th
        Unit
      %th
        Ingredient
      %th.actions

    = render partial: 'ingredient', collection: recipe.recipe_ingredients

  = link_to 'Add Ingredient', new_recipe_recipe_ingredient_path(recipe), class: "btn btn-default"

app/views/recipes/_ingredient.html.haml
= form_for(ingredient) do |f|
  %tr
    = f.hidden_field :recipe_id
    %td
      = f.number_field :amount
    %td
      = ingredient.ingredient.unit
    %td
      = f.select(:ingredient_id, grouped_options_for_select(Ingredient.by_category, ingredient.id))
    %td
      = f.submit "Save", class: "btn btn-primary"
      = link_to 'Delete', ingredient, data: {:confirm => 'Are you sure?'}, method: :delete, class: "btn btn-default"

app/views/recipes/_recipe.html.haml
%tr
  %td
    = link_to recipe.name, recipe
  %td
    = number_with_precision(recipe.energy, precision: 0)
  %td
    = number_with_precision(recipe.carbo, precision: 1)
  %td
    = number_with_precision(recipe.protein, precision: 1)
  %td
    = number_with_precision(recipe.fat, precision: 1)

app/views/recipes/index.html.haml
.row
  %h1
    Recipes

  %table.table.table-striped.table-hover
    %thead
      %tr
        %th
          Name
        %th
          Energy
        %th
          Carbohydrates
        %th
          Protein
        %th
          Fat


    %tbody
      = render partial: 'recipe', collection: @recipes

  = link_to 'New Recipe', new_recipe_path, class: "btn btn-default"

app/views/recipes/new.html.haml
%h1
  New Recipe

= render 'form', recipe: @recipe

app/views/recipes/show.html.haml
%h1
  Edit Recipe

= render 'form', recipe: @recipe