config/routes.rb
Rails.application.routes.draw do
  resources :ingredients, only: %i[index show new create update destroy]
  resources :ingredient_categories, only: %i[index show new create update destroy]
  resources :recipes, only: %i[index show new create update destroy] do
    resources :recipe_ingredients, only: %i[new]
  end
  resources :recipe_ingredients, only: %i[create update destroy]
  resources :mealtimes, only: %i[index show new create update destroy] do
    resources :recipe_meals, only: %i[new]
    resources :ingredient_meals, only: %i[new]
    resources :custom_meals, only: %i[new show]
  end
  resources :recipe_meals, only: %i[create update destroy]
  resources :ingredient_meals, only: %i[create update destroy]
  resources :custom_meals, only: %i[create update destroy]
  resources :protocols, only: %i[index show new]
  resources :weight_protocol_entries, only: %i[create update destroy]

  namespace :api do
    namespace :v1 do
      resources :ingredients, only: %i[index show create update destroy]
      resources :ingredient_categories, only: %i[index show create update destroy]
    end
  end
end

app/views/shared/_navbar_left.html.haml
.left-sidebar-wrapper
  %a.left-sidebar-toggle{:href => "#", :title => "Dashboard"}
    Dashboard
  .left-sidebar-spacer
    .left-sidebar-scroll
      .left-sidebar-content
        %ul.sidebar-elements
          %li.divider Ingredients
          %li
            = link_to ingredients_url do
              %i.zmdi.zmdi-home
              Ingredients

app/views/shared/_navbar_top.html.haml
.container-fluid
  .navbar-header
    %button.navbar-toggle.collapsed{'type' => 'button', 'data-toggle' => 'collapse', 'data-target' => '#navbar-collapse', 'aria-expanded' => 'false'}
      %span.sr-only
        Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
      = link_to('Diet Mate', ingredients_url,  {:class => "navbar-brand"} )

  #navbar-collapse.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li.active
        %a{:href => "#"}
          DietMate
          %span.sr-only (current)
      %li
        = link_to "IngredientCategories", ingredient_categories_path
      %li
        = link_to "Ingredients", ingredients_path
      %li
        = link_to "Recipes", recipes_path
      %li
        = link_to "Mealtimes", mealtimes_path
      %li
        = link_to "Protocol", protocols_path