config/routes.rb
Rails.application.routes.draw do
  resources :ingredients, only: %i[index show new create update destroy]
  resources :ingredient_categories, only: %i[index show new create update destroy]
  resources :recipes, only: %i[index show new create update destroy] do
    resources :recipe_ingredients, only: %i[new]
  end
  resources :recipe_ingredients, only: %i[create update destroy]
  resources :mealtimes, only: %i[index show new create update destroy] do
    resources :recipe_meals, only: %i[new]
    resources :ingredient_meals, only: %i[new]
    resources :custom_meals, only: %i[new show]
  end
  resources :recipe_meals, only: %i[create update destroy]
  resources :ingredient_meals, only: %i[create update destroy]
  resources :custom_meals, only: %i[create update destroy]
  resources :protocols, only: %i[index show new]
  resources :weight_protocol_entries, only: %i[create update destroy]

  namespace :api do
    namespace :v1 do
      resources :ingredients, only: %i[index show create update destroy]
      resources :ingredient_categories, only: %i[index show create update destroy]
    end
  end
end

app/models/mealtime.rb
class Mealtime < ApplicationRecord
  has_many :meals
  has_many :ingredient_meals

  def energy
    sum = 0
    meals.each do |meal|
      sum += meal.energy
    end
    sum
  end

  def carbo
    sum = 0
    meals.each do |meal|
      sum += meal.carbo
    end
    sum
  end

  def protein
    sum = 0
    meals.each do |meal|
      sum += meal.protein
    end
    sum
  end

  def fat
    sum = 0
    meals.each do |meal|
      sum += meal.fat
    end
    sum
  end
end

app/controllers/mealtimes_controller.rb
class MealtimesController < ApplicationController
  before_action :set_mealtime, only: %i[show update destroy]

  # GET /mealtimes
  def index
    dates = Mealtime.all.select("DATE(date) AS dist_date").distinct
    @sections = []
    dates.each do |date|
      @sections << MealSection.new(date["dist_date"])
    end

    puts @sections.to_json
    @mealtimes = Mealtime.all.order(:date)
    calculate_totals
  end

  # GET /mealtimes/1
  def show; end

  # GET /mealtimes/new
  def new
    @mealtime = Mealtime.new
  end

  # POST /mealtimes
  def create
    @mealtime = Mealtime.new(mealtime_params)

    if @mealtime.save
      redirect_to @mealtime, notice: 'Mealtime was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /mealtimes/1
  def update
    if @mealtime.update(mealtime_params)
      redirect_to @mealtime, notice: 'Mealtime was successfully updated.'
    else
      render :show
    end
  end

  # DELETE /mealtimes/1
  def destroy
    @mealtime.destroy
    redirect_to mealtimes_url, notice: 'Mealtime was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_mealtime
    @mealtime = Mealtime.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def mealtime_params
    params.require(:mealtime).permit(:title, :date)
  end

  def calculate_totals
    @total_energy = 0
    @total_carbo = 0
    @total_protein = 0
    @total_fat = 0
    @mealtimes.each do |meal|
      @total_energy += meal.energy
      @total_carbo += meal.carbo
      @total_protein += meal.protein
      @total_fat += meal.fat
    end
  end
end

app/views/mealtimes/_form.html.haml
= bootstrap_form_for(mealtime) do |f|
  - if mealtime.errors.any?
    #error_explanation
      %h2
        = pluralize(mealtime.errors.count, "error")
        prohibited this mealtime from being saved:

      %ul
      - mealtime.errors.full_messages.each do |message|
        %li
          = message

  = f.text_field :title
  = f.date_field :date

  .actions
    = f.submit "Save", class: "btn btn-primary"
    - if mealtime.persisted?
      = link_to 'Delete', mealtime, data: {:confirm => 'Are you sure?'}, method: :delete, class: "btn btn-default"
    = link_to 'Back', mealtimes_path, class: "btn btn-default"

- if mealtime.persisted?
  %table
    %tr
      %th
        Title
      %th
        Amount
      %th
        Energy
      %th
        Carbohydrates
      %th
        Protein
      %th
        Fat
      %th.actions

    = render partial: 'meal', collection: mealtime.meals

  = link_to 'Add Recipe Meal', new_mealtime_recipe_meal_path(mealtime), class: "btn btn-default"

  = link_to 'Add Ingredient Meal', new_mealtime_ingredient_meal_path(mealtime), class: "btn btn-default"

  = link_to 'Add Custom Meal', new_mealtime_custom_meal_path(mealtime), class: "btn btn-default"

app/views/mealtimes/_meal.html.haml
= form_for(meal) do |f|
  %tr
    = f.hidden_field :mealtime_id
    - if meal.recipe_meal?
      %td
        = f.collection_select(:recipe_id, Recipe.all, :id, :name)
      %td
        = f.number_field :amount
    - if meal.ingredient_meal?
      %td
        = f.collection_select(:ingredient_id, Ingredient.all, :id, :name)
      %td
        = f.number_field :amount
    - if meal.custom_meal?
      %td{ colspan: 2 }
        = link_to meal.name, mealtime_custom_meal_path(meal.mealtime, meal)
    %td
      = number_with_precision(meal.energy, precision: 0)
    %td
      = number_with_precision(meal.carbo, precision: 1)
    %td
      = number_with_precision(meal.protein, precision: 1)
    %td
      = number_with_precision(meal.fat, precision: 1)
    %td
      - unless meal.custom_meal?
        = f.submit "Save", class: "btn btn-primary"
      = link_to 'Delete', meal, data: {:confirm => 'Are you sure?'}, method: :delete, class: "btn btn-default"

app/views/mealtimes/_meal_section.html.haml
= render partial: 'mealtime', collection: meal_section.mealtimes

%tr
  %td
    Total
  %td
  %td
    = number_with_precision(meal_section.total_energy, precision: 0)
  %td
    = number_with_precision(meal_section.total_carbo, precision: 1)
  %td
    = number_with_precision(meal_section.total_protein, precision: 1)
  %td
    = number_with_precision(meal_section.total_fat, precision: 1)

app/views/mealtimes/_mealtime.html.haml
%tr
  %td
    = link_to mealtime.title, mealtime
  %td
    = mealtime.date
  %td
    = number_with_precision(mealtime.energy, precision: 0)
  %td
    = number_with_precision(mealtime.carbo, precision: 1)
  %td
    = number_with_precision(mealtime.protein, precision: 1)
  %td
    = number_with_precision(mealtime.fat, precision: 1)

app/views/mealtimes/index.html.haml
.row
  %h1
    Mealtimes

  %table.table.table-striped.table-hover
    %thead
      %tr
        %th
          Title
        %th
          Date
        %th
          Energy
        %th
          Carbohydrates
        %th
          Protein
        %th
          Fat

    %tbody
      = render partial: 'meal_section', collection: @sections

  = link_to 'New Mealtime', new_mealtime_path, class: "btn btn-default"

app/views/mealtimes/new.html.haml
%h1
  New Mealtime

= render 'form', mealtime: @mealtime

app/views/mealtimes/show.html.haml
%h1
  Edit Mealtime

= render 'form', mealtime: @mealtime