config/routes.rb
Rails.application.routes.draw do
  resources :ingredients, only: %i[index show new create update destroy]
  resources :ingredient_categories, only: %i[index show new create update destroy]
  resources :recipes, only: %i[index show new create update destroy] do
    resources :recipe_ingredients, only: %i[new]
  end
  resources :recipe_ingredients, only: %i[create update destroy]
  resources :mealtimes, only: %i[index show new create update destroy] do
    resources :recipe_meals, only: %i[new]
    resources :ingredient_meals, only: %i[new]
    resources :custom_meals, only: %i[new show]
  end
  resources :recipe_meals, only: %i[create update destroy]
  resources :ingredient_meals, only: %i[create update destroy]
  resources :custom_meals, only: %i[create update destroy]
  resources :protocols, only: %i[index show new]
  resources :weight_protocol_entries, only: %i[create update destroy]

  namespace :api do
    namespace :v1 do
      resources :ingredients, only: %i[index show create update destroy]
      resources :ingredient_categories, only: %i[index show create update destroy]
    end
  end
end

app/controllers/protocols_controller.rb
class ProtocolsController < ApplicationController
  before_action :set_weight_protocol_entry, only: %i[show]

  # GET /weight_protocol_entries
  def index
    @weight_protocol_entries = WeightProtocolEntry.all.order(:date)
  end

  # GET /weight_protocol_entries/1
  def show; end

  # GET /weight_protocol_entries/new
  def new
    @weight_protocol_entry = WeightProtocolEntry.new
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_weight_protocol_entry
    @weight_protocol_entry = WeightProtocolEntry.find(params[:id])
  end
end

app/views/protocols/_form.html.haml
= bootstrap_form_for(protocol) do |f|
  - if protocol.errors.any?
    #error_explanation
      %h2
        = pluralize(protocol.errors.count, "error")
        prohibited this protocol from being saved:

      %ul
      - protocol.errors.full_messages.each do |message|
        %li
          = message

  = f.text_field :date
  = f.select(:sex, WeightProtocolEntry.sexes.keys.map { |sex| [ sex.humanize, sex ]})
  = f.number_field :weight, step: 0.1
  = f.number_field :height
  = f.number_field :waist, step: 0.1
  = f.number_field :hip, step: 0.1
  = f.number_field :neck, step: 0.1

  .actions
    = f.submit "Save", class: "btn btn-primary"
    - if protocol.persisted?
      = link_to 'Delete', protocol, data: {:confirm => 'Are you sure?'}, method: :delete, class: "btn btn-default"
    = link_to 'Back', protocols_path, class: "btn btn-default"

app/views/protocols/_protocol_entry.html.haml
%tr
  %td
    = link_to protocol_entry.date, protocol_path(protocol_entry)
  %td
    = protocol_entry.sex.humanize
  %td
    = number_with_precision(protocol_entry.weight, precision: 1)
  %td
    = number_with_precision(protocol_entry.height, precision: 0)
  %td
    = number_with_precision(protocol_entry.waist, precision: 1)
  %td
    = number_with_precision(protocol_entry.hip, precision: 1)
  %td
    = number_with_precision(protocol_entry.neck, precision: 1)
  %td
    = number_with_precision(protocol_entry.bmi, precision: 1)
  %td
    = number_with_precision(protocol_entry.navy_fat, precision: 1)
    -# %

app/views/protocols/index.html.haml
.row
  %h1
    Protocol

  %table.table.table-striped.table-hover
    %thead
      %tr
        %th
          Date
        %th
          Sex
        %th
          Weight
        %th
          Height
        %th
          Waist
        %th
          Hip
        %th
          Neck
        %th
          BMI
        %th
          BodyFat (NavyMethod)


    %tbody
      = render partial: 'protocol_entry', collection: @weight_protocol_entries

  = link_to 'New protocol entry', new_protocol_path, class: "btn btn-default"

app/views/protocols/new.html.haml
%h1
  Add protocol entry

= render 'protocols/form', protocol: @weight_protocol_entry

app/views/protocols/show.html.haml
%h1
  Edit protocol entry

= render 'protocols/form', protocol: @weight_protocol_entry